[package]
name = "gdfc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
steamid-ng = "1.*"

[dependencies.steamlocate]
version = "0.*"
features = ["steamid_ng"]